// Auto-generated by scripts/generate-licenses.mjs. Do not edit manually.

export interface ComponentInfo {
  name: string;
  license: string;
}

export const rustComponents: ComponentInfo[] = [
  {
    "name": "async-tungstenite",
    "license": "MIT"
  },
  {
    "name": "base64",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "bytes",
    "license": "MIT"
  },
  {
    "name": "dirs",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "flate2",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "futures-util",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "hotdownloader",
    "license": "Apache-2.0"
  },
  {
    "name": "lofty",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "log",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "once_cell",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "open",
    "license": "MIT"
  },
  {
    "name": "rand",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "regex",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "reqwest",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "rumqttc",
    "license": "Apache-2.0"
  },
  {
    "name": "rustls",
    "license": "Apache-2.0 OR ISC OR MIT"
  },
  {
    "name": "serde",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "serde_json",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-build",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-android-fs",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-dialog",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-log",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-notification",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-opener",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-os",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tauri-plugin-store",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "tokio",
    "license": "MIT"
  },
  {
    "name": "tokio-util",
    "license": "MIT"
  },
  {
    "name": "umc_qmc",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "url",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "urlencoding",
    "license": "MIT"
  }
];

export const frontendComponents: ComponentInfo[] = [
  {
    "name": "@tauri-apps/api",
    "license": "Apache-2.0 OR MIT"
  },
  {
    "name": "@tauri-apps/plugin-dialog",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "@tauri-apps/plugin-os",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "@tauri-apps/plugin-store",
    "license": "MIT OR Apache-2.0"
  },
  {
    "name": "dompurify",
    "license": "(MPL-2.0 OR Apache-2.0)"
  },
  {
    "name": "marked",
    "license": "MIT"
  },
  {
    "name": "naive-ui",
    "license": "MIT"
  },
  {
    "name": "pinia",
    "license": "MIT"
  },
  {
    "name": "semver",
    "license": "ISC"
  },
  {
    "name": "vue",
    "license": "MIT"
  },
  {
    "name": "vue-router",
    "license": "MIT"
  }
];
